name: test
on:
  workflow_dispatch:
  push:
    branches:
      - 11-github-tag-bump-test
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=ref,event=tag
            
      - name: Install & Test
        run: |
          yarn
          yarn test
      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kumsil1006
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        

            
      - name: print meta
        run: |
          echo ${{ steps.meta.outputs.tags }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
