name: test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    tags:
      - 'v.**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: print meta
        run: |
          echo ${{ steps.tag_version.outputs.new_tag }}
          echo ${{ steps.tag_version.outputs.changelog }}          

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          
      - name: print new release version
        run: |
          echo ${{ steps.tag_version.outputs.new_tag }}
